webtalk_init -webtalk_dir C:/Users/natha/Projects/SpaceInvaders/SpaceInvaders.sim/sim_1/behav/xsim/xsim.dir/pixel_clk_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Oct 21 22:22:15 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3286242" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "7946e758-1bf8-4505-9df5-3cb7183cbb8a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f2da4a950a8c47aca320c735dd8cfed5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "14" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 9 3950X 16-Core Processor            " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3493 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7580_KB" -context "xsim\\usage"
webtalk_transmit -clientid 600139721 -regid "" -xml C:/Users/natha/Projects/SpaceInvaders/SpaceInvaders.sim/sim_1/behav/xsim/xsim.dir/pixel_clk_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/natha/Projects/SpaceInvaders/SpaceInvaders.sim/sim_1/behav/xsim/xsim.dir/pixel_clk_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/natha/Projects/SpaceInvaders/SpaceInvaders.sim/sim_1/behav/xsim/xsim.dir/pixel_clk_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
